// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMM43GHoD7J3ZyU0AcGs3YRHT_jGwtl30',
    appId: '1:615106312330:web:6ade2d20e870e8e3151573',
    messagingSenderId: '615106312330',
    projectId: 'act12-a77a4',
    authDomain: 'act12-a77a4.firebaseapp.com',
    storageBucket: 'act12-a77a4.firebasestorage.app',
    measurementId: 'G-W866HNW8VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvYpJTiRHOmRX7jMdegDQGCkv4vkPPewE',
    appId: '1:615106312330:android:114ad41db0798e10151573',
    messagingSenderId: '615106312330',
    projectId: 'act12-a77a4',
    storageBucket: 'act12-a77a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEMwHZUeE7hkVIGzdyRGNEf3RSuEV5dLE',
    appId: '1:615106312330:ios:7a5f354601a45363151573',
    messagingSenderId: '615106312330',
    projectId: 'act12-a77a4',
    storageBucket: 'act12-a77a4.firebasestorage.app',
    iosBundleId: 'com.example.act12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEMwHZUeE7hkVIGzdyRGNEf3RSuEV5dLE',
    appId: '1:615106312330:ios:7a5f354601a45363151573',
    messagingSenderId: '615106312330',
    projectId: 'act12-a77a4',
    storageBucket: 'act12-a77a4.firebasestorage.app',
    iosBundleId: 'com.example.act12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMM43GHoD7J3ZyU0AcGs3YRHT_jGwtl30',
    appId: '1:615106312330:web:5667c4449cdad1ea151573',
    messagingSenderId: '615106312330',
    projectId: 'act12-a77a4',
    authDomain: 'act12-a77a4.firebaseapp.com',
    storageBucket: 'act12-a77a4.firebasestorage.app',
    measurementId: 'G-F18S4KWPGC',
  );
}
